# Generated by Django 4.1.2 on 2022-11-04 01:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PercentualComissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Domingo'), (1, 'Segunda'), (2, 'Terca'), (3, 'Quarta'), (4, 'Quinta'), (5, 'Sexta'), (6, 'Sabado')], unique=True)),
                ('minimo', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(0.1)])),
                ('maximo', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(0.1)])),
            ],
        ),
    ]
