# Generated by Django 4.1.2 on 2022-11-05 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0001_initial'),
        ('cliente', '0001_initial'),
        ('venda', '0003_produtovenda_delete_vendaproduto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente', to='cliente.cliente'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data_hora',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='venda',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendedor', to='vendedor.vendedor'),
        ),
    ]
