# Generated by Django 4.1.2 on 2022-11-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0006_alter_itemvenda_produto_alter_itemvenda_venda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='percentualcomissao',
            name='dia_semana',
            field=models.IntegerField(choices=[(0, 'Segunda'), (1, 'Terca'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sabado'), (6, 'Domingo')], unique=True),
        ),
    ]
