# Generated by Django 4.1.2 on 2022-11-01 00:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(max_length=255)),
                ('valor_unitario', models.FloatField(validators=[django.core.validators.MinValueValidator('0.01')])),
                ('percentual_comissao', models.FloatField(validators=[django.core.validators.MinValueValidator('0.01'), django.core.validators.MaxValueValidator('0.1')])),
            ],
        ),
    ]
