# Generated by Django 4.1.2 on 2022-11-01 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_produto_percentual_comissao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
